from batch import BatchScript

s = BatchScript()
s.set_job_name("test1")
s.set_reservation("now")
s.set_command("python3 ~/Worm/EffectiveBorromeanWorm/find_constant_curve/test_open.py")
s.set_run_time(100)
s.set_output_name("out")
s.set_log_name("1")
s.run_batch()
s.set_log_name("2")
s.run_batch()
s.set_log_name("3")
s.run_batch()
s.set_log_name("4")
s.run_batch()
s.set_log_name("5")
s.run_batch()
s.set_log_name("6")
s.run_batch()
s.set_log_name("7")
s.run_batch()
s.set_log_name("8")
s.run_batch()
s.set_log_name("9")
s.run_batch()
s.set_log_name("10")
s.run_batch()